"""empty message

Revision ID: c30688a13fa2
Revises: 95e3220eae7b
Create Date: 2026-09-20 19:39:37.770401

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c30688a13fa2'
down_revision = '95e3220eae7b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('wilaya_delivery_fees',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('wilaya_code', sa.Integer(), nullable=False),
    sa.Column('wilaya_name', sa.String(length=60), nullable=False),
    sa.Column('fee', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('wilaya_code')
    )
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.add_column(sa.Column('wilaya_code', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('wilaya_name', sa.String(length=60), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.drop_column('wilaya_name')
        batch_op.drop_column('wilaya_code')

    op.drop_table('wilaya_delivery_fees')
    # ### end Alembic commands ###
